import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Guides sidebar
  guidesSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    // Add more docs here as you create them:
    // {
    //   type: "category",
    //   label: "User Guides",
    //   items: ["user-guide/projects"],
    // },
  ],

  // API Reference sidebar (auto-generated by OpenAPI plugin)
  // Note: Run `bun run docs:generate` after starting the API server to generate API docs
  apiSidebar: [
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "generated-index",
        title: "Asset-Forge API",
        description:
          "Complete API reference for Asset-Forge 3D asset generation platform. Run 'bun run docs:generate' to generate API reference from OpenAPI spec.",
        slug: "/api-reference",
      },
      items: [],
      // Uncomment after running `bun run docs:generate`:
      // items: require("./docs/api-reference/sidebar.js"),
    },
  ],
};

export default sidebars;
