/**
 * Generation Pipelines Schema
 * Matches the actual database structure from migration 0023_loud_shen.sql
 */

import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  jsonb,
  integer,
  index,
  pgEnum,
} from "drizzle-orm/pg-core";
import { users } from "./users.schema";
import { assets } from "./assets.schema";

// Enums (must match database)
export const pipelineStatus = pgEnum("pipeline_status", [
  "initializing",
  "processing",
  "completed",
  "failed",
  "cancelled",
]);

/**
 * Generation pipelines table
 * IMPORTANT: This schema MUST match the actual database structure exactly
 * See migration: server/db/migrations/0023_loud_shen.sql
 */
export const generationPipelines = pgTable(
  "generation_pipelines",
  {
    // Primary key - UUID generated by database
    id: uuid("id").defaultRandom().primaryKey(),

    // Foreign keys
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id").references(() => assets.id, {
      onDelete: "set null",
    }),

    // Pipeline configuration and state
    config: jsonb("config").notNull(),
    status: pipelineStatus("status").notNull().default("initializing"),
    progress: integer("progress").notNull().default(0),

    // Current execution state
    currentStage: varchar("current_stage", { length: 100 }),
    error: text("error"),
    errorStage: varchar("error_stage", { length: 100 }),
    errorDetails: jsonb("error_details"),

    // Results from pipeline execution
    results: jsonb("results").notNull().default({}),

    // External service task IDs
    meshyTaskId: varchar("meshy_task_id", { length: 255 }),
    riggingTaskId: varchar("rigging_task_id", { length: 255 }),

    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    // Cleanup tracking
    expiresAt: timestamp("expires_at", { withTimezone: true }),
  },
  (table) => ({
    // Indexes (must match migration)
    userIdx: index("idx_pipelines_user").on(table.userId),
    assetIdx: index("idx_pipelines_asset").on(table.assetId),
    statusIdx: index("idx_pipelines_status").on(table.status),
    createdIdx: index("idx_pipelines_created").on(table.createdAt.desc()),
    expiresIdx: index("idx_pipelines_expires").on(table.expiresAt),
    userStatusIdx: index("idx_pipelines_user_status").on(
      table.userId,
      table.status,
    ),
    meshyTaskIdx: index("idx_pipelines_meshy_task").on(table.meshyTaskId),
  }),
);

// Type exports
export type GenerationPipeline = typeof generationPipelines.$inferSelect;
export type NewGenerationPipeline = typeof generationPipelines.$inferInsert;
