/**
 * OpenAPI Specification Export
 * Provides the raw OpenAPI JSON spec for external documentation tools (e.g., Docusaurus)
 *
 * Endpoint:
 * - GET /api/openapi.json: Returns the complete OpenAPI 3.0 specification
 */

import { Elysia } from "elysia";

/**
 * OpenAPI export route
 *
 * This endpoint exposes the raw OpenAPI JSON specification generated by the swagger plugin.
 * It's publicly accessible (no authentication required) to allow external documentation tools
 * like Docusaurus to consume the API spec.
 *
 * The spec is dynamically generated from the Elysia app's routes and swagger configuration.
 */
export const openapiRoutes = new Elysia({
  prefix: "/api",
  name: "openapi",
}).get(
  "/openapi.json",
  (context) => {
    // The Elysia swagger plugin automatically generates and exposes the OpenAPI spec
    // We access it through the router's schema which is built from all registered routes
    const app = (context as any).store?.app || (context as any).app;

    // Get the OpenAPI schema from the app's routes
    // The swagger plugin builds this from the app's route definitions
    if (app?.getSchemaObject) {
      const schema = app.getSchemaObject();
      return schema;
    }

    // Fallback: try to access via the route definitions
    const spec = (context as any).store?.openapi || (app as any).openapi;

    if (!spec) {
      return {
        error: "OpenAPI specification not available",
        message:
          "Swagger plugin may not be configured correctly. The spec is available at /swagger/json",
      };
    }

    return spec;
  },
  {
    detail: {
      tags: ["Documentation"],
      summary: "Get OpenAPI specification",
      description:
        "Returns the complete OpenAPI 3.0 specification in JSON format. This endpoint is publicly accessible and designed for consumption by external documentation tools like Docusaurus.",
      responses: {
        200: {
          description: "OpenAPI specification returned successfully",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  openapi: { type: "string", example: "3.0.0" },
                  info: {
                    type: "object",
                    properties: {
                      title: { type: "string" },
                      version: { type: "string" },
                      description: { type: "string" },
                    },
                  },
                  paths: { type: "object" },
                  components: { type: "object" },
                },
              },
            },
          },
        },
        500: {
          description: "OpenAPI spec not available",
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  error: { type: "string" },
                  message: { type: "string" },
                },
              },
            },
          },
        },
      },
    },
  },
);
